name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-modmenu
        path: out/magisk_module_release/
